package com.aicontentanalyser.analysis.image.infrastructure;

import com.aicontentanalyser.analysis.image.domain.ImageDetectionResult;
import com.aicontentanalyser.analysis.image.domain.ImageDetector;
import org.apache.hc.client5.http.classic.methods.HttpPost;
import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
import org.apache.hc.client5.http.impl.classic.HttpClients;
import org.apache.hc.client5.http.entity.mime.MultipartEntityBuilder;
import org.apache.hc.core5.http.HttpEntity;
import org.apache.hc.core5.http.ContentType;
import org.apache.hc.core5.http.io.entity.EntityUtils;
import org.springframework.stereotype.Component;
import com.fasterxml.jackson.databind.ObjectMapper;


@Component
public class MLServiceImageDetector implements ImageDetector {

    private static final String ML_SERVICE_URL =
            "http://localhost:8000/predict";

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Override
    public ImageDetectionResult detect(byte[] image) {

        try (CloseableHttpClient client = HttpClients.createDefault()) {

            HttpPost post = new HttpPost(ML_SERVICE_URL);

            HttpEntity entity = MultipartEntityBuilder.create()
                    .addBinaryBody(
                            "image",
                            image,
                            ContentType.IMAGE_JPEG,
                            "image.jpg"
                    )
                    .build();

            post.setEntity(entity);

            System.out.println("RAW Content-Type: " + entity.getContentType());
            System.out.println("Request headers: " + java.util.Arrays.toString(post.getHeaders()));

            MLServiceResponse response =
                    client.execute(post, httpResponse -> {

                        String json =
                                EntityUtils.toString(httpResponse.getEntity());

                        return objectMapper.readValue(
                                json,
                                MLServiceResponse.class
                        );
                    });

            return new ImageDetectionResult(
                    response.prediction(),
                    response.confidence(),
                    "Prediction generated by the image ML service.",
                    response.modelVersion()
            );

        } catch (Exception e) {
            throw new RuntimeException("Failed to call ML service", e);
        }
    }
}